server:
  port: 8080
 
spring:
  h2:
    console:
      enabled: true
      path:  /h2-console  
  datasource:
    dbcp2:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:~/test
      username: pc
      password: 2024
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    hibernate:
      ddl-auto: update
    open-in-view: false